### ISSUE TITLE
Post to Discord Missing

### ISSUE THREAD

**Issue by LtPsych** [aussig/BGS-Tally#32]
The Post to Discord Button is missing.

for a few days everything was fine now its missing

**Comment by Sakurax64** [comment]
This issue can be closed.
See https://github.com/aussig/BGS-Tally/pull/33

**Comment by aussig** [comment]
Sorry I've only just seen this.

As @Sakurax64 mentions in his patch, the issue is caused because Discord have changed their webhook URLs from `https://discord.com/api/webhooks/xxxxx` to `https://discordapp.com/api/webhooks/`.

The plugin does a rudimentary check on the URL just to ensure it looks like a correct Discord webhook and this check is now failing for the new style URLs.

I actually fixed this in commit 73e9aa93f1db30ec05f42e6ab4e8be5c424dd70f but I like @Sakurax64 's fix better as it accounts for more URL formats, so I'll merge that change in.
